### ISSUE TITLE
Referencing tables

### ISSUE THREAD

**Issue by sorsted** [Witiko/markdown#159] opened 2022-07-31 14:38 UTC
There currently seems to be no interface for referencing tables (other than with `hybrid=true` and LaTeX code). For instance, the following doesn’t work:

```latex
\documentclass{article}

\usepackage[headerAttributes,relativeReferences,pipeTables,tableCaptions]{markdown}

\begin{document}

\begin{markdown}

## This is a heading {#thissection}

This is section <#thissection>


| Hello | World |
| ----- | ----- |
| Happy | World |

: Hello {#mytable}

This is <#mytable>

\end{markdown}

\end{document}
```

**Comment by Witiko** [comment] 2022-07-31 19:27
Closing as a duplicate of https://github.com/Witiko/markdown/issues/123#issuecomment-1124010273.

**Closed by Witiko** 2022-07-31 19:27 UTC
