### ISSUE TITLE
bugs about math blocks in markdown environment

### ISSUE THREAD

**Issue by yfzhao20** [Witiko/markdown#94] opened 2021-08-10 16:22 UTC
Hi! When I use `$$...$$` (math  blocks) in markdown environment, it gives me a thousand bugs😂 like that:

![image](https://user-images.githubusercontent.com/80528249/128896006-5e8aea9e-1f2a-4140-90cf-c752f9a962a1.png)

Here is my file: 

``` tex
\documentclass[UTF8]{ctexart}
\usepackage[hybrid]{markdown}
\usepackage{amsmath}
\begin{document}
\begin{markdown}
$$
\begin{aligned}
\cos^n\theta&=\left(\frac{e^{i\theta}+e^{-i\theta}}{2}\right)^n\\
&=(\frac{1}{2})^n(\sum\limits_{m=0}^{n}\tbinom{n}{m}e^{i\theta(n-2m)})\\
&=(\frac{1}{2})^n(\sum\limits_{m=0}^{n}\tbinom{n}{m}\frac{e^{i\theta(n-2m)}+e^{-i\theta(n-2m)}}{2})\\
&=(\frac{1}{2})^n(\sum\limits_{m=0}^{n}\tbinom{n}{m}\cos(n-2m)\theta)\\
\sin^n\theta&=\left(\frac{e^{i\theta}-e^{-i\theta}}{2i}\right)^n\\
&=(\frac{1}{2i})^n(\sum\limits_{m=0}^{n}\tbinom{n}{m}e^{i\theta(n-2m)}(-1)^m)\\
&=(\frac{1}{2i})^2(\sum\limits_{m=1}^{n}\tbinom{n}{m}\frac{e^{i\theta(n-2m)}i^{2m}+e^{i\theta(2m-n)}i^{2(n-m)}}{2})\\
&=(\frac{1}{2})^n(\sum\limits_{m=1}^{n}\tbinom{n}{m}\frac{e^{i\theta(n-2m)}(-i)^{n-2m}+e^{-i\theta(n-2m)}i^{n-2m}}{2})\\
&=(\frac{1}{2})^n(\sum\limits_{m=0}^{n}\tbinom{n}{m}\frac{e^{i(\theta-\frac{\pi}{2})(n-2m)}+e^{-i(\theta-\frac{\pi}{2})(n-2m)}}{2})\\
&=(\frac{1}{2})^n(\sum\limits_{m=0}^{n}\tbinom{n}{m}\cos(n-2m)(\theta-\frac{\pi}{2}))\\
\end{aligned}
$$
\end{markdown}
\end{document}
```

however if I only keep the first two lines of my math formula, everything will be okay:

``` tex
\documentclass[UTF8]{ctexart}
\usepackage[hybrid]{markdown}
\usepackage{amsmath}
\begin{document}
\begin{markdown}
$$
\begin{aligned}
\cos^n\theta&=\left(\frac{e^{i\theta}+e^{-i\theta}}{2}\right)^n\\
&=(\frac{1}{2})^n(\sum\limits_{m=0}^{n}\tbinom{n}{m}e^{i\theta(n-2m)})\\
\end{aligned}
$$
\end{markdown}
\end{document}
```

The code of math block should be okay because I have tested it in Markdown editor. It should be displayed like this:

![image](https://user-images.githubusercontent.com/80528249/128896128-52e0bc78-2c46-42e3-8662-b2fbf1b7c885.png)

What's the matter? Is it the bug of `markdown` package, or my fault?🤔

by the way: I find only `\\\\` can give me correct line break in math block but not `\\`, even I open "hybrid".

Thanks!!

**Comment by Witiko** [comment] 2021-08-10 21:09
@yfzhao20 It's best to drop out of Markdown before math blocks: `\\` and `_` will get interpreted by Markdown as `\` and the beginning of emphasized text, which will give you a hard time. You can disable the interpretation of `_` for emphasis by specifying the `underscores=false` option, but you still have to write `\\\\` for the `\\`.

I am closing this issue as a duplicate of #61.

**Closed by Witiko** 2021-08-10 21:09 UTC

**Comment by yfzhao20** [comment] 2021-08-11 03:20
Ah! It works after I let `underscores=false`✅. But I still have to write `\\\\` for `\\` . Thanks🎉!
![image](https://user-images.githubusercontent.com/80528249/128964330-febbb979-6d8f-490c-b460-183e5b1df892.png)
